/****************************************************************************
 * arch/risc-v/src/sty32c2/hardware/sty32c2_sdio.h
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_RISCV_SRC_STY32C2_HARDWARE_STY32C2_SDIO_H
#define __ARCH_RISCV_SRC_STY32C2_HARDWARE_STY32C2_SDIO_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include "hardware/sty32c2_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* STY32C2_SDIO register offsets **********************************************/

#define STY32C2_SDBLOCK2MEM_DMA_BASE_OFFSET   0x0000
#define STY32C2_SDBLOCK2MEM_DMA_LENGTH_OFFSET 0x0008
#define STY32C2_SDBLOCK2MEM_DMA_ENABLE_OFFSET 0x000C
#define STY32C2_SDBLOCK2MEM_DMA_DONE_OFFSET   0x0010
#define STY32C2_SDBLOCK2MEM_DMA_LOOP_OFFSET   0x0014
#define STY32C2_SDBLOCK2MEM_DMA_OFFSET_OFFSET 0x0018

#define STY32C2_SDCORE_CMD_ARGUMENT_OFFSET    0x0000
#define STY32C2_SDCORE_CMD_COMMAND_OFFSET     0x0004
#define STY32C2_SDCORE_CMD_SEND_OFFSET        0x0008
#define STY32C2_SDCORE_CMD_RESPONSE_OFFSET    0x000C
#define STY32C2_SDCORE_CMD_EVENT_OFFSET       0x001C
#define STY32C2_SDCORE_DATA_EVENT_OFFSET      0x0020
#define STY32C2_SDCORE_BLOCK_LENGTH_OFFSET    0x0024
#define STY32C2_SDCORE_BLOCK_COUNT_OFFSET     0x0028

#define STY32C2_SDIRQ_STATUS_OFFSET           0x0000
#define STY32C2_SDIRQ_PENDING_OFFSET          0x0004
#define STY32C2_SDIRQ_ENABLE_OFFSET           0x0008

#define STY32C2_SDMEM2BLOCK_DMA_BASE_OFFSET   0x0000
#define STY32C2_SDMEM2BLOCK_DMA_LENGTH_OFFSET 0x0008
#define STY32C2_SDMEM2BLOCK_DMA_ENABLE_OFFSET 0x000C
#define STY32C2_SDMEM2BLOCK_DMA_DONE_OFFSET   0x0010
#define STY32C2_SDMEM2BLOCK_DMA_LOOP_OFFSET   0x0014
#define STY32C2_SDMEM2BLOCK_DMA_OFFSET_OFFSET 0x0018

#define STY32C2_SDPHY_CARD_DETECT_OFFSET      0x0000
#define STY32C2_SDPHY_CLOCKER_DIVIDER_OFFSET  0x0004
#define STY32C2_SDPHY_INIT_INITIALIZE_OFFSET  0x0008
#define STY32C2_SDPHY_DATAW_STATUS_OFFSET     0x000C

/* STY32C2_SDIO register addresses ********************************************/

#define STY32C2_SDBLOCK2MEM_DMA_BASE          (STY32C2_SDBLOCK2MEM_BASE+STY32C2_SDBLOCK2MEM_DMA_BASE_OFFSET)
#define STY32C2_SDBLOCK2MEM_DMA_LENGTH        (STY32C2_SDBLOCK2MEM_BASE+STY32C2_SDBLOCK2MEM_DMA_LENGTH_OFFSET)
#define STY32C2_SDBLOCK2MEM_DMA_ENABLE        (STY32C2_SDBLOCK2MEM_BASE+STY32C2_SDBLOCK2MEM_DMA_ENABLE_OFFSET)
#define STY32C2_SDBLOCK2MEM_DMA_DONE          (STY32C2_SDBLOCK2MEM_BASE+STY32C2_SDBLOCK2MEM_DMA_DONE_OFFSET)
#define STY32C2_SDBLOCK2MEM_DMA_LOOP          (STY32C2_SDBLOCK2MEM_BASE+STY32C2_SDBLOCK2MEM_DMA_LOOP_OFFSET)
#define STY32C2_SDBLOCK2MEM_DMA_OFFSET        (STY32C2_SDBLOCK2MEM_BASE+STY32C2_SDBLOCK2MEM_DMA_OFFSET_OFFSET)

#define STY32C2_SDCORE_CMD_ARGUMENT           (STY32C2_SDCORE_BASE+STY32C2_SDCORE_CMD_ARGUMENT_OFFSET)
#define STY32C2_SDCORE_CMD_COMMAND            (STY32C2_SDCORE_BASE+STY32C2_SDCORE_CMD_COMMAND_OFFSET)
#define STY32C2_SDCORE_CMD_SEND               (STY32C2_SDCORE_BASE+STY32C2_SDCORE_CMD_SEND_OFFSET)
#define STY32C2_SDCORE_CMD_RESPONSE           (STY32C2_SDCORE_BASE+STY32C2_SDCORE_CMD_RESPONSE_OFFSET)
#define STY32C2_SDCORE_CMD_EVENT              (STY32C2_SDCORE_BASE+STY32C2_SDCORE_CMD_EVENT_OFFSET)
#define STY32C2_SDCORE_DATA_EVENT             (STY32C2_SDCORE_BASE+STY32C2_SDCORE_DATA_EVENT_OFFSET)
#define STY32C2_SDCORE_BLOCK_LENGTH           (STY32C2_SDCORE_BASE+STY32C2_SDCORE_BLOCK_LENGTH_OFFSET)
#define STY32C2_SDCORE_BLOCK_COUNT            (STY32C2_SDCORE_BASE+STY32C2_SDCORE_BLOCK_COUNT_OFFSET)

#define STY32C2_SDIRQ_STATUS                  (STY32C2_SDIRQ_BASE+STY32C2_SDIRQ_STATUS_OFFSET)
#define STY32C2_SDIRQ_PENDING                 (STY32C2_SDIRQ_BASE+STY32C2_SDIRQ_PENDING_OFFSET)
#define STY32C2_SDIRQ_ENABLE                  (STY32C2_SDIRQ_BASE+STY32C2_SDIRQ_ENABLE_OFFSET)

#define STY32C2_SDMEM2BLOCK_DMA_BASE          (STY32C2_SDMEM2BLOCK_BASE+STY32C2_SDMEM2BLOCK_DMA_BASE_OFFSET)
#define STY32C2_SDMEM2BLOCK_DMA_LENGTH        (STY32C2_SDMEM2BLOCK_BASE+STY32C2_SDMEM2BLOCK_DMA_LENGTH_OFFSET)
#define STY32C2_SDMEM2BLOCK_DMA_ENABLE        (STY32C2_SDMEM2BLOCK_BASE+STY32C2_SDMEM2BLOCK_DMA_ENABLE_OFFSET)
#define STY32C2_SDMEM2BLOCK_DMA_DONE          (STY32C2_SDMEM2BLOCK_BASE+STY32C2_SDMEM2BLOCK_DMA_DONE_OFFSET)
#define STY32C2_SDMEM2BLOCK_DMA_LOOP          (STY32C2_SDMEM2BLOCK_BASE+STY32C2_SDMEM2BLOCK_DMA_LOOP_OFFSET)
#define STY32C2_SDMEM2BLOCK_DMA_OFFSET        (STY32C2_SDMEM2BLOCK_BASE+STY32C2_SDMEM2BLOCK_DMA_OFFSET_OFFSET)

#define STY32C2_SDPHY_CARD_DETECT             (STY32C2_SDPHY_BASE+STY32C2_SDPHY_CARD_DETECT_OFFSET)
#define STY32C2_SDPHY_CLOCKER_DIVIDER         (STY32C2_SDPHY_BASE+STY32C2_SDPHY_CLOCKER_DIVIDER_OFFSET)
#define STY32C2_SDPHY_INIT_INITIALIZER        (STY32C2_SDPHY_BASE+STY32C2_SDPHY_INIT_INITIALIZE_OFFSET)
#define STY32C2_SDPHY_DATAW_STATUS            (STY32C2_SDPHY_BASE+STY32C2_SDPHY_DATAW_STATUS_OFFSET)

/* STY32C2_SDIO register bit definitions **************************************/

#endif /* __ARCH_RISCV_SRC_STY32C2_HARDWARE_STY32C2_SDIO_H */
